"""Add validation_acknowledged to Kontakt

Revision ID: 855daa6bf681
Revises: d6c21ed8ffc9
Create Date: 2025-10-02 12:13:00.123456

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "855daa6bf681"
down_revision = "d6c21ed8ffc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kontakt", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "validation_acknowledged",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kontakt", schema=None) as batch_op:
        batch_op.drop_column("validation_acknowledged")
    # ### end Alembic commands ###
