"""Add allow_multiselect to Eigenschaft

Revision ID: ade54f99eb33
Revises: 90ced2d3e5b4
Create Date: 2025-09-29 09:18:00.123456

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ade54f99eb33"
down_revision = "90ced2d3e5b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eigenschaft", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "allow_multiselect", sa.Boolean(), nullable=False, server_default="0"
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eigenschaft", schema=None) as batch_op:
        batch_op.drop_column("allow_multiselect")
    # ### end Alembic commands ###
