"""Add import_raw_content to Kontakt

Revision ID: d6c21ed8ffc9
Revises: ade54f99eb33
Create Date: 2025-10-02 09:56:04.196147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c21ed8ffc9'
down_revision = 'ade54f99eb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kontakt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_raw_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kontakt', schema=None) as batch_op:
        batch_op.drop_column('import_raw_content')

    # ### end Alembic commands ###
